root = "."
tmp_dir = "tmp"
build = "mkdir -p {{.tmp}} && go build -o {{.tmp}}/main"
cmd = "{{.tmp}}/main"
include_ext = ["go", "tmpl", "tpl", "html"]
exclude_dir = ["tmp", "vendor"]
exclude_ext = ["sqlite3"]
