FROM golang:1.23-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest

RUN apk add --no-cache gcc musl-dev sqlite-dev

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080

CMD ["air"]
